package by.epam.validation.service.validation;

public enum ErrorValidation
{
	EMPTY_LOGIN, INCORRECT_LOGIN, EMPTY_PASSWORD, INCORRECT_PASSWORD,
	EMPTY_NICKNAME, INCORRECT_NICKNAME, EMPTY_EMAIL, INCORRECT_EMAIL,
	EMPTY_PHONE_NUMBER, INCORRECT_PHONE_NUMBER
}
